export interface Rocket {
    id?: number,
    sourceId?: string | null,
    sourceUrl?: string | null,
    name: string,
    fullName: string,
    family: string,
    active: boolean,
    reusable: boolean,
    description: string,
    variant: string,
    length: number,
    diameter: number,
    maidenFlight: string,
    lastLaunchDate: string | null,
    launchCost: number | null,
    launchMass: number,
    leoCapacity: number,
    gtoCapacity: number | null,
    imageUrl: string,
    wikiUrl: string,
    totalLaunchCount: number,
    successfulLaunchCount: number,
    failedLaunchCount: number
}
